### ISSUE TITLE
MS Windows 10 Pro (WSL) error ERR_UNKNOWN_STDIN_TYPE

### ISSUE THREAD

**Issue by lfurzewaddock** [conradz/tap-webpack-plugin#8]
**Environment**

- Windows 10 Pro: v1709
- Windows Subsystem for Linux (WSL) - Ubuntu 16.04.3 LTS
- Node: v8.4.0
- npm: v5.3.0
- webpack v3.10.0
- tape v4.8.0
- tap-webpack-plugin v2.0.0

**Error**

internal/process/stdio.js:99
        throw new errors.Error('ERR_UNKNOWN_STDIN_TYPE');
        ^

Error [ERR_UNKNOWN_STDIN_TYPE]: Unknown stdin file type
    at process.getStdin [as stdin] (internal/process/stdio.js:99:15)
    at startup (bootstrap_node.js:186:18)
    at bootstrap_node.js:598:3
internal/process/stdio.js:99
        throw new errors.Error('ERR_UNKNOWN_STDIN_TYPE');
        ^

Error [ERR_UNKNOWN_STDIN_TYPE]: Unknown stdin file type
    at process.getStdin [as stdin] (internal/process/stdio.js:99:15)
    at Object.<anonymous> (/mnt/d/Users/Projects/Dev/node_modules/tap-spec/bin/cmd.js:6:8)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by mindplay-dk** [comment]
Same error here.

* Win 10 Pro: 1709 (same)
* node: 9.5.0
* npm: 5.7.1
* webpack: 4.4.1
* tape: 4.9.0
* tap-webpack-plugin: 2.0.0

**Comment by mindplay-dk** [comment]
Looks like the issue was tracked [here](https://github.com/Microsoft/WSL/issues/1774) but closed without resolution (??)
